config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'

  get 'contact/create'

  resources :contacts, only: [:new, :create] 
  resources :comments
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'orders/create'

 resources :products, only: :index do
 	resources :orders, only: :create
 end

 resources :orders, only: :index do
 	collection do
 		get 'clean'
 		get 'payed'
 	end
 end

 resources :billings, only: [:index] do
 	collection do
 		get 'pre_pay'
 		get 'execute'
 end
end 

 root to: 'products#index'
 devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
class Ability
  include CanCan::Ability

      def initialize(user)
        user ||= User.new
       # if user.admin?
           if user.admin?
                can :manage, :all
           else
                can :read, :all
           end
      end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :surname,   :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone,     :validate => true

  attribute :message,  	:validate => true
  

  def headers
    {
      :subject => "Consultas de compras",
      :to => "joselin.solis.3b@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true

  scope :cart, -> {where(payed: false)}
  scope :payed, -> {where(payed: true)}
  
  def self.get_total
 	pluck("price * quantity").sum()
  end 

  def self.total_quantity
  	pluck("quantity").sum()
  end

 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders

	mount_uploader :photo, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	has_many :orders
	has_many :billings
	has_many :products, through: :orders
	has_many :posts

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		 user.email = auth.info.email
		 user.password = Devise.friendly_token[0,20]
		 #user.name = auth.info.name
		end
	end

	def is_admin?
    	current_user.admin == 1
 	end
end

app/controllers/billings_controller.rb
require 'paypal-sdk-rest'
class BillingsController < ApplicationController
	before_action :authenticate_user!

	def index
		@billings = current_user.billings
	end

	def pre_pay
		orders = current_user.orders.cart #where(payed: false)
		total = orders.get_total
		items = get_items_hash(orders)
		

			@payment = PayPal::SDK::REST::Payment.new({
	  		:intent =>  "sale",
	  		:payer =>  {
	 		:payment_method =>  "paypal" },
	  		:redirect_urls => {
	    	#:return_url => "http://localhost:3000/billings/execute",
	    	#:cancel_url => "http://localhost:3000/" },
	    	:return_url => "https://ancient-peak-20736.herokuapp.com//billings/execute",
	    	:cancel_url => "https://ancient-peak-20736.herokuapp.com/" },
	  		:transactions =>  [{
	    	:item_list => {
	     	:items => items
	     	},
	    	:amount =>  {
	     	:total =>  total,
	      	:currency =>  "USD" },
	    	:description =>  "Carro de compras" }]})

		if @payment.create
			redirect_url = @payment.links.find{|v| v.method == "REDIRECT"}.href
			redirect_to redirect_url
		else
			render json: @payment.error
		end

	end

	def execute
		paypal_payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
		
		if paypal_payment.execute(payer_id: params[:PayerID])
		
		amount = paypal_payment.transactions.first.amount.total

		billing = Billing.create(
			user: current_user,
			code: paypal_payment.id,
			payment_method: 'paypal',
			amount: amount,
			currency: 'USD'
			)

		orders = current_user.orders.where(payed: false)
		orders.update_all(payed: true, billing_id: billing.id)

		redirect_to root_path, notice: "La compra se realizó con éxito!"
	else
		render plain: "No se puedo generar el cobro en PayPal."
	end
		
	end

	private
	def get_items_hash(orders)
		items = orders.map do |order|
			item = {}
			item[:name]	= order.product.name
			item[:sku] = order.id.to_s
			item[:price] = order.price.to_s
			item[:currency] = 'USD'
			item[:quantity] = order.quantity
			item
	    end
		
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!

  def create
  	@product = Product.find(params[:product_id])
  	#@order = Order.new(product: @product, user: current_user)
    @order = Order.find_or_create_by(user: current_user, product: @product, payed: false, price: @product.price)
    @order.quantity += 1

  	if @order.save
  		redirect_to products_path, notice: 'El producto ha sido añadido al carro de compras'
  	else
  		redirect_to products_path, alert: 'El producto no ha sido añadido al carro de compras'
  	end
  end

  def index
  	#@orders = Order.where(user: current_user, payed: false)
    @orders = current_user.orders.cart
    @total = @orders.get_total
  end

  def payed
    @orders = current_user.orders.payed
   #@total = @orders.get_total
    @orders_id = @orders.pluck(:billing_id).uniq!
    
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
  	def index
	  	@products = Product.all
	  	@contact = Contact.new
  	end

  	def mount_uploader
  	
  	end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end 

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h2 align="center">Productos</h2> 
  </div>
</div>

<div class="flex-section-container" >
	<div class="container">
		 <% @products.each_slice(4) do |row| %>			
		  <div class="row" id='products_row'>
		  <% row.each do |product|%>
			  <div class="col-md-3">
			    <%= image_tag product.photo, size: '250x250' %>
			    <p><%= product.name%></p>
				<p>$<%= product.price %></p>
				<%= link_to "Añadir", product_orders_path(product), class: 'btn btn-info', method: :post %>
			   </div>
		  	  <% end %>
	       </div>
	    <% end %>		
	</div>
</div>

<div class="jumbotron">
  <div class="container">
    <h2 align="center">Información</h2> 
  </div>
</div>

<footer id="footer">
	<div class="container">
		<div class="col-md-3">
			<div class="row">
				<%= form_for @contact do |f| %>
				<div class="row">
					<div class="col-md-6">
						<%= f.label :name, "Nombre" %><br>
						<%= f.text_field :name, required: true , class:'form-control' %>
					</div>
					<div class="col-md-6">
						<%= f.label :surname, "Apellido" %><br>
						<%= f.text_field :surname, required: true, class:'form-control' %>
					</div>
				</div>
				<div class="row">
					<div>
						<%= f.label :email, "Email" %><br>
						<%= f.text_field :email, required: true, class:'form-control' %>
					</div>
				</div>
				<div class="row">
					<div>
						<%= f.label :phone, "Teléfono" %><br>
						<%= f.text_field :phone, required: true, class:'form-control' %>
					</div>
				</div>
				<div class="row">
					<div>
						<%= f.label :message, "Mensaje" %><br>
						<%= f.text_area :message, required: true, class:'form-control' %>
					</div>
				</div>
				<div class="row">
					<div >
					<br>
						<%= f.submit "Enviar", class: 'btn btn-info' %>
					</div>
				</div>	
			<% end %>
			</div>
		</div>
		
	
		<div class="col-md-5">
			<div class="redes-sociales">
				<h3>Información de contacto</h3>
					<ul>
					    <li>
						 	<a href="http://www.facebook.com" target="_blank">
						   		<%= image_tag 'facebook.png', width: 60, height: 60%>
						 	</a>
						</li>
						<li>
						 	<a href="http://www.twitter.com" target="_blank">	
						   		<%= image_tag 'twitter.png', width: 60, height: 60%>
						    </a>
						</li>
					
						<li>
							<a href="http://www.linkedin.com" target="_blank">
							   <%= image_tag 'linkedin.png', width: 60, height: 60%>
							</a>
						</li>
						<li>
							<a href="http://www.instagram.com" target="_blank">
							   <%= image_tag 'instagram.png', width: 60, height: 60%>
							</a>
						</li>
						<li>
							<a href="http://www.youtube.com" target="_blank">
							   	<%= image_tag 'youtube.png', width: 60, height: 60%>
							</a>
						</li>
					</ul>
			</div>
			<div class="direccion">
				<div class="direccion">
					<span class="glyphicon glyphicon-map-marker"></span>
					Miguel Claro 1074, Providencia
				</div>
			</div>
			<div class="email">
				<div class="email">
					<span class="glyphicon glyphicon-envelope"></span>
					  <a href="mail:ayuda@shoppingcart.cl">ayuda@shoppingcart.cl</a>
				</div>
			</div>
			<div class="telefono">
				<div class="telefono">
					<span class="glyphicon glyphicon-earphone"></span>
					<a href="tel: + 56 9 1234 5678">+ 56 9 1234 5678</a>
				</div>
			</div>
		</div>

		<div class="col-md-4">
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3329.393649757302!2d-70.62057344954661!3d-33.4390493042183!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cf7f0bf2766b%3A0x3b9d62e2ef6661e1!2sJos%C3%A9+Miguel+Claro+1074%2C+Providencia%2C+Regi%C3%B3n+Metropolitana!5e0!3m2!1ses-419!2scl!4v1520093667876" width="350" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</div>
</footer>