config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'

  get 'contact/create'

  resources :contacts, only: [:new, :create] 
  resources :comments
  resources :posts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'orders/create'

 resources :products, only: :index do
 	resources :orders, only: :create
 end

 resources :orders, only: :index do
 	collection do
 		get 'clean'
 		get 'payed'
 	end
 end

 resources :billings, only: [:index] do
 	collection do
 		get 'pre_pay'
 		get 'execute'
 end
end 

 root to: 'products#index'
 devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
class Ability
  include CanCan::Ability

      def initialize(user)
        user ||= User.new
       # if user.admin?
           if user.admin?
                can :manage, :all
           else
                can :read, :all
           end
      end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :surname,   :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone,     :validate => true

  attribute :message,  	:validate => true
  

  def headers
    {
      :subject => "Consultas de compras",
      :to => "joselin.solis.3b@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true

  scope :cart, -> {where(payed: false)}
  scope :payed, -> {where(payed: true)}
  
  def self.get_total
 	pluck("price * quantity").sum()
  end 

  def self.total_quantity
  	pluck("quantity").sum()
  end

 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :users, through: :orders

	mount_uploader :photo, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

	has_many :orders
	has_many :billings
	has_many :products, through: :orders
	has_many :posts

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		 user.email = auth.info.email
		 user.password = Devise.friendly_token[0,20]
		 #user.name = auth.info.name
		end
	end

	def is_admin?
    	current_user.admin == 1
 	end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base

  private

    def post_params
      params.require(:post).permit(:user_id, :title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	end 

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= products_path%>">JoySA Shopping</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= orders_path %>">Carrito de compras</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="<%= payed_orders_path%>">Ordenes de compra</a></li>
      </ul>          
      <ul class="nav navbar-nav">
       <%if current_user.try(:admin?) %>
         <li><a href="<%=admin_root_path%>">Admin</a><li>
       <% end %>
      </ul>     
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?%>
        <li><a href="#">Bienvenido(a): <%= current_user.email %></a></li>
      		<% else %>
         <li><a href="<%=new_user_session_path%>">Ingreso</a></li>
          <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
          aria-haspopup="true" aria-expanded="false"><span class="caret"></span>Menu</a>
           
          <ul class="dropdown-menu">
            <%if user_signed_in? %>           
            <li><a href="<%=edit_user_registration_path%>">Actualizar datos </a></li>
            <li><a href="<%=destroy_user_session_path%>" data-method='DELETE'>Salir</a>
            </li>
            <%else%>
            <li><a href="<%=new_user_session_path%>">Ingreso</a></li>
            <li><a href="<%=new_user_registration_path%>">Registro</a></li>
            <%end%>
          </ul>
        </li>
      </ul>

	
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script
    src="https://code.jquery.com/jquery-2.2.4.min.js"
     integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
      crossorigin="anonymous"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
    <title>Shopping cart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'icono.ico' %>
  </head>

  <body>
  <%=render 'layouts/navbar' %>
  <% if notice.present? %>
   <div class="alert alert-success" role="alert">
     <%= notice%>
   </div>
  <% end %>
  <% if alert.present? %>
   <div class="alert alert-danger" role="alert">
     <%= alert%>
   </div>
  <% end %>
  
    <%= yield %>
  </body>

  
</html>